package:
  name: capella-sarpy
  version: 1.1.66

source:
  path: ../..

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - setuptools_scm

  run:
    - python
    - numpy
    - scipy

about:
    home: https://gitlab.corp.capellaspace.com/sar/sarpy
