package:
  name: capella-sarpy
  version: 0.0.9

source:
  path: ../..

requirements:
  build:
    - python
    - setuptools
    - numpy
    - setuptools_scm

  run:
    - python
    - numpy

about:
    home: https://gitlab.corp.capellaspace.com/sar/sarpy
